#!/usr/bin/env bash
# Kept in the Agent context so both independent Docker builds can use this tool.
set -euo pipefail

output=${1:?Usage: third-party-notices.sh OUTPUT PACKAGE [FRONTEND_NOTICES] [CERTIFICATE_COPYRIGHT]}
package=${2:?Missing Go entry point}
frontend=${3:-}
certificates=${4:-}
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
trap 'exit 1' HUP INT TERM

# Build the collector for the host, then inspect the package with the caller's
# GOOS, GOARCH, CGO_ENABLED and GOFLAGS (the same settings as the release build).
GOBIN="$work/bin" GOOS="$(go env GOHOSTOS)" GOARCH="$(go env GOHOSTARCH)" GOFLAGS= \
  go install github.com/google/go-licenses/v2@v2.0.1
cat > "$work/report.tmpl" <<'TEMPLATE'
{{range .}}{{printf "%s\t%s\t%s\t%s\n" .Name .Version .LicenseName .LicensePath}}{{end -}}
TEMPLATE
"$work/bin/go-licenses" report "$package" --ignore github.com/RSTCK-Innovation/arveld \
  --template "$work/report.tmpl" > "$work/report.tsv"
[[ -s "$work/report.tsv" ]] || { echo 'No Go dependency licenses found.' >&2; exit 1; }
module_cache=$(go env GOMODCACHE)
goroot=$(go env GOROOT)
go_license="$goroot/LICENSE"
# Homebrew stores the toolchain license next to libexec rather than inside it.
[[ -s "$go_license" ]] || go_license="$(dirname "$goroot")/LICENSE"
touch "$work/seen"

append_document() {
  local file=$1 label=$2
  [[ -s "$file" && -f "$file" ]] || { echo "Missing licensing document: $label" >&2; exit 1; }
  if ! grep -Fxq "$file" "$work/seen"; then
    printf '\n--- %s ---\n\n' "$label"
    cat "$file"
    printf '\n'
    printf '%s\n' "$file" >> "$work/seen"
  fi
}

{
  cat <<'HEADER'
THIRD-PARTY NOTICES

This file preserves upstream license texts and attribution notices for this
build's Go dependencies and, for the controller, its bundled frontend.
Arveld's own license and notice are provided in LICENSE and NOTICE.

Unmodified Go module source archives are available at the versioned URLs below,
under their respective licenses (including the Mozilla Public License where
applicable). This file does not replace those terms or the release's SPDX inventory.
HEADER
  printf '\nGo runtime and standard library: %s\n' "$(go env GOVERSION)"
  append_document "$go_license" 'Go/LICENSE'
  # The standard library vendors upstream packages with their own license files.
  while IFS= read -r file; do
    append_document "$file" "Go/${file#"$goroot/"}"
  done < <(find "$goroot/src/vendor" -type f -name LICENSE | LC_ALL=C sort)

  while IFS=$'\t' read -r name version license file; do
    [[ -n "$name" && "$version" != Unknown && "$license" != Unknown ]] || \
      { echo "Unresolved dependency license: $name" >&2; exit 1; }
    case "$file" in
      "$module_cache/"*@*/*) ;;
      *) echo "Expected a downloaded, versioned module for $name; review local replacements before distribution." >&2; exit 1 ;;
    esac
    relative=${file#"$module_cache/"}
    module_path=${relative%%@*}
    module_version=${relative#*@}
    module_version=${module_version%%/*}
    module_root="$module_cache/$module_path@$module_version"
    if grep -Fxq "$file" "$work/seen"; then continue; fi
    printf '\n============================================================\n%s %s\n' "$name" "$version"
    printf 'Source: https://proxy.golang.org/%s/@v/%s.zip\n' "$module_path" "$module_version"
    append_document "$file" "${file#"$module_root/"}"
    directory=$(dirname "$file")
    while :; do
      for extra in "$directory"/*; do
        [[ -f "$extra" ]] || continue
        case "$(basename "$extra" | tr '[:lower:]' '[:upper:]')" in
          NOTICE*|COPYRIGHT*|AUTHORS*|PATENTS*) append_document "$extra" "${extra#"$module_root/"}" ;;
        esac
      done
      [[ "$directory" != "$module_root" ]] || break
      directory=$(dirname "$directory")
    done
  done < "$work/report.tsv"

  if [[ -n "$frontend" ]]; then
    printf '\n============================================================\nBundled frontend (including fonts)\n'
    append_document "$frontend" 'Frontend licenses generated by Vite'
  fi
  if [[ -n "$certificates" ]]; then
    # Only the Mozilla certificate data is copied into runtime images, not the
    # Debian package's GPL-licensed maintenance utilities.
    awk '/^Files: / { keep = ($0 == "Files: mozilla/certdata.txt") } keep { print }' \
      "$certificates" > "$work/certificates.txt"
    grep -Fq 'Mozilla Public License Version 2.0' "$work/certificates.txt"
    certificate_version=$(dpkg-query -W -f='${Version}' ca-certificates)
    printf '\nCertificate roots: ca-certificates %s\n' "$certificate_version"
    printf 'Source: https://sources.debian.org/src/ca-certificates/%s/\n' "$certificate_version"
    append_document "$work/certificates.txt" 'Mozilla certificate data copyright and license'
  fi
} > "$work/THIRD_PARTY_NOTICES.txt"

mkdir -p "$(dirname "$output")"
cp "$work/THIRD_PARTY_NOTICES.txt" "$output"
printf 'Generated %s\n' "$output"
