//go:build docker

package integration

import (
	"bytes"
	"compress/gzip"
	"context"
	"crypto/rand"
	"encoding/json"
	"errors"
	"io"
	"maps"
	"net"
	"net/http"
	"net/http/httptest"
	"os/exec"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"go.opentelemetry.io/collector/pdata/pmetric"
	"golang.org/x/net/dns/dnsmessage"

	"github.com/RSTCK-Innovation/arveld/internal/agent"
	"github.com/RSTCK-Innovation/arveld/internal/remoteconfig"
	"github.com/RSTCK-Innovation/arveld/tests/testutil"
)

func TestSupervisorExecutesNetworkMonitors(t *testing.T) {
	var pingSucceeded atomic.Bool
	var networkCollected atomic.Bool
	// The sink verifies an actual successful ICMP measurement, not just configuration acceptance.
	sink := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var reader io.Reader = r.Body
		if r.Header.Get("Content-Encoding") == "gzip" {
			decompress, err := gzip.NewReader(r.Body)
			if err != nil {
				t.Error(err)
				w.WriteHeader(http.StatusBadRequest)
				return
			}
			defer func() {
				if err := decompress.Close(); err != nil {
					t.Error(err)
				}
			}()
			reader = decompress
		}
		body, err := io.ReadAll(reader)
		if err != nil {
			t.Error(err)
			w.WriteHeader(http.StatusBadRequest)
			return
		}
		decoder := pmetric.ProtoUnmarshaler{}
		exported, err := decoder.UnmarshalMetrics(body)
		if err != nil {
			t.Error(err)
			w.WriteHeader(http.StatusBadRequest)
			return
		}
		resources := exported.ResourceMetrics()
		for i := range resources.Len() {
			resource := resources.At(i)
			_, monitorMetric := resource.Resource().Attributes().Get("arveld.monitor.id")
			scopes := resource.ScopeMetrics()
			for j := range scopes.Len() {
				metrics := scopes.At(j).Metrics()
				for k := range metrics.Len() {
					metric := metrics.At(k)
					if !monitorMetric && metric.Name() == "system.network.io" && metric.Type() == pmetric.MetricTypeSum && metric.Unit() == "By" {
						points := metric.Sum().DataPoints()
						for p := range points.Len() {
							point := points.At(p)
							device, _ := point.Attributes().Get("device")
							direction, _ := point.Attributes().Get("direction")
							if device.Str() != "" && direction.Str() == "receive" && point.IntValue() > 0 {
								networkCollected.Store(true)
							}
						}
					}
					if monitorMetric && metric.Name() == "ping.loss.ratio" && metric.Type() == pmetric.MetricTypeGauge {
						points := metric.Gauge().DataPoints()
						if points.Len() > 0 && points.At(0).DoubleValue() == 0 {
							pingSucceeded.Store(true)
						}
					}
				}
			}
		}
		w.Header().Set("Content-Type", "application/x-protobuf")
		w.WriteHeader(http.StatusOK)
	}))
	t.Cleanup(sink.Close)
	tcpAddress, tcpConnections := networkTCPFixture(t)
	dnsAddress, dnsQueries := networkDNSFixture(t)
	config := controllerConfig(t, sink.URL)
	config.HTTPAddress = "0.0.0.0:0"
	db := testutil.OpenDatabase(t, config.DatabasePath)
	createAdministrator(t, db)
	token := createAgentKey(t, db)
	controllerURL, _ := startController(t, config)
	container := "arveld-network-test-" + rand.Text()
	docker := func(args ...string) {
		t.Helper()
		ctx, cancel := context.WithTimeout(t.Context(), 30*time.Second)
		defer cancel()
		if output, err := exec.CommandContext(ctx, "docker", args...).CombinedOutput(); err != nil { //nolint:gosec // Test-owned argument list, without a shell.
			t.Fatalf("docker %s: %v\n%s", args[0], err, output)
		}
	}
	docker("run", "--detach", "--name", container,
		"--add-host", "host.docker.internal:host-gateway",
		"--env", "ARVELD_AGENT_TOKEN="+token, "--env", "ARVELD_URL="+dockerHostURL(t, controllerURL),
		"--volume", "/:/hostfs:ro", "--volume", "/var/lib/arveld-agent",
		"arveld-agent:0.161.0-arveld")
	t.Cleanup(func() {
		ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
		defer cancel()
		if t.Failed() {
			logs, err := exec.CommandContext(ctx, "docker", "logs", "--tail", "100", container).CombinedOutput() //nolint:gosec // The container name is generated by this test.
			t.Logf("Supervisor logs (%v):\n%s", err, logs)
		}
		if output, err := exec.CommandContext(ctx, "docker", "rm", "--force", "--volumes", container).CombinedOutput(); err != nil { //nolint:gosec // The container name is generated by this test.
			t.Errorf("remove network test container: %v\n%s", err, output)
		}
	})
	var uid agent.InstanceUID
	store := remoteconfig.NewStore(db)
	awaitSupervisor(t, "initial Agent application and network byte collection", func() bool {
		values, err := agent.NewStore(db).List(t.Context())
		if err != nil {
			t.Fatal(err)
		}
		if len(values) != 1 {
			return false
		}
		uid = values[0].InstanceUID
		status, err := store.Status(t.Context(), uid)
		return err == nil && status.State == remoteconfig.ApplyStatusApplied && networkCollected.Load()
	})
	cookie := loginController(t, controllerURL)
	create := func(protocol, endpoint string, settings map[string]any) {
		t.Helper()
		input := map[string]any{"name": "Network " + protocol, "agent_instance_uid": uid.String(), "endpoint": endpoint, "interval_seconds": 10, "timeout_seconds": 3}
		maps.Copy(input, settings)
		body, err := json.Marshal(input)
		if err != nil {
			t.Fatal(err)
		}
		request, err := http.NewRequestWithContext(t.Context(), http.MethodPost, controllerURL+"/api/v1/monitors/"+protocol, bytes.NewReader(body))
		if err != nil {
			t.Fatal(err)
		}
		request.Header.Set("Content-Type", "application/json")
		request.AddCookie(cookie)
		response := doControllerRequest(t, request)
		if err := response.Body.Close(); err != nil {
			t.Fatal(err)
		}
		if response.StatusCode != http.StatusCreated {
			t.Fatalf("create %s = %d", protocol, response.StatusCode)
		}
	}
	for _, value := range []struct {
		protocol, endpoint string
		settings           map[string]any
	}{
		{"tcp", tcpAddress, nil},
		{"icmp", "127.0.0.1", map[string]any{"ping_count": 2}},
		{"dns", "arveld.example", map[string]any{"dns_server": dnsAddress, "record_type": "A", "transport": "udp"}},
	} {
		create(value.protocol, value.endpoint, value.settings)
	}
	awaitSupervisor(t, "TCP connection, DNS query, successful ICMP and applied revision", func() bool {
		status, err := store.Status(t.Context(), uid)
		if err != nil {
			t.Fatal(err)
		}
		return status.State == remoteconfig.ApplyStatusApplied && status.LastWorking != nil &&
			*status.LastWorking.Revision == status.Desired.Number && tcpConnections.Load() > 0 && dnsQueries.Load() > 0 && pingSucceeded.Load()
	})

	before, err := store.Desired(t.Context(), uid)
	if err != nil {
		t.Fatal(err)
	}
	countBefore := tcpConnections.Load()
	docker("stop", "--time", "5", container)
	awaitSupervisor(t, "Agent disconnection", func() bool {
		values, err := agent.NewStore(db).List(t.Context())
		if err != nil {
			t.Fatal(err)
		}
		return len(values) == 1 && !values[0].Connected
	})
	create("tcp", tcpAddress, nil)
	offline, err := store.Desired(t.Context(), uid)
	if err != nil || offline.Number != before.Number+1 {
		t.Fatalf("offline creation did not publish: %+v, %v", offline, err)
	}
	docker("start", container)
	awaitSupervisor(t, "offline Monitor application after reconnect", func() bool {
		status, err := store.Status(t.Context(), uid)
		if err != nil {
			t.Fatal(err)
		}
		return status.State == remoteconfig.ApplyStatusApplied && status.LastWorking != nil &&
			*status.LastWorking.Revision == offline.Number && tcpConnections.Load() > countBefore
	})
	if err := store.ReconcileAgent(t.Context(), uid); err != nil {
		t.Fatal(err)
	}
	unchanged, err := store.Desired(t.Context(), uid)
	if err != nil || unchanged.Number != offline.Number {
		t.Fatalf("reconnect added a duplicate revision: %v", err)
	}
	t.Logf("observed %d TCP connections, %d DNS queries and zero ICMP loss", tcpConnections.Load(), dnsQueries.Load())
}

func networkTCPFixture(t *testing.T) (string, *atomic.Int64) {
	t.Helper()
	var listen net.ListenConfig
	listener, err := listen.Listen(t.Context(), "tcp", "0.0.0.0:0")
	if err != nil {
		t.Fatal(err)
	}
	var count atomic.Int64
	done := make(chan struct{})
	go func() {
		defer close(done)
		for {
			connection, err := listener.Accept()
			if err != nil {
				if !errors.Is(err, net.ErrClosed) {
					t.Error(err)
				}
				return
			}
			count.Add(1)
			if err := connection.Close(); err != nil {
				t.Error(err)
			}
		}
	}()
	t.Cleanup(func() {
		if err := listener.Close(); err != nil {
			t.Error(err)
		}
		<-done
	})
	return strings.TrimPrefix(dockerHostURL(t, "http://"+listener.Addr().String()), "http://"), &count
}

func networkDNSFixture(t *testing.T) (string, *atomic.Int64) {
	t.Helper()
	var listen net.ListenConfig
	connection, err := listen.ListenPacket(t.Context(), "udp", "0.0.0.0:0")
	if err != nil {
		t.Fatal(err)
	}
	var count atomic.Int64
	done := make(chan struct{})
	go func() {
		defer close(done)
		buffer := make([]byte, 4096)
		for {
			n, address, err := connection.ReadFrom(buffer)
			if err != nil {
				if !errors.Is(err, net.ErrClosed) {
					t.Error(err)
				}
				return
			}
			var query dnsmessage.Message
			if err := query.Unpack(buffer[:n]); err != nil {
				t.Error(err)
				return
			}
			if len(query.Questions) != 1 || query.Questions[0].Name.String() != "arveld.example." || query.Questions[0].Type != dnsmessage.TypeA {
				t.Errorf("unexpected DNS query: %+v", query)
				return
			}
			count.Add(1)
			response := dnsmessage.Message{
				ID: query.ID, Response: true, RecursionDesired: query.RecursionDesired, RecursionAvailable: true,
				Questions: query.Questions,
				Answers:   []dnsmessage.Resource{{Header: dnsmessage.ResourceHeader{Name: query.Questions[0].Name, Type: dnsmessage.TypeA, Class: dnsmessage.ClassINET, TTL: 60}, Body: &dnsmessage.AResource{A: [4]byte{127, 0, 0, 1}}}},
			}
			body, err := response.Pack()
			if err != nil {
				t.Error(err)
				return
			}
			if _, err := connection.WriteTo(body, address); err != nil {
				t.Error(err)
				return
			}
		}
	}()
	t.Cleanup(func() {
		if err := connection.Close(); err != nil {
			t.Error(err)
		}
		<-done
	})
	return strings.TrimPrefix(dockerHostURL(t, "http://"+connection.LocalAddr().String()), "http://"), &count
}
