//go:build docker

package integration

import (
	"bytes"
	"compress/gzip"
	"context"
	"crypto/rand"
	"encoding/json"
	"errors"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"os/exec"
	"slices"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"go.opentelemetry.io/collector/pdata/pmetric"

	"github.com/RSTCK-Innovation/arveld/internal/agent"
	"github.com/RSTCK-Innovation/arveld/internal/remoteconfig"
	"github.com/RSTCK-Innovation/arveld/tests/testutil"
)

func TestSupervisorAppliesCompiledMonitorAndRecoversLocally(t *testing.T) {
	for _, mode := range []string{"mounted-host", "native-root"} {
		t.Run(mode, func(t *testing.T) {
			exerciseSupervisorConfiguration(t, mode)
		})
	}
}

func exerciseSupervisorConfiguration(t *testing.T, mode string) {
	t.Helper()
	// The target and OTLP sink are local fixtures reachable from the container.
	var probes atomic.Int64
	var hostMetrics atomic.Bool
	endpoint := httptest.NewUnstartedServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/health" {
			body, err := io.ReadAll(r.Body)
			if err != nil || r.Method != http.MethodPost || string(body) != `{"ready":"$literal"}` || r.Header.Get("Authorization") != "Bearer $synthetic" || r.Header.Get("Content-Type") != "application/json" {
				t.Errorf("compiled HTTP request lost method/body/headers: method=%s, read error=%v", r.Method, err)
			} else {
				probes.Add(1)
			}
			_, _ = w.Write([]byte(`{"ready":true}`)) //nolint:errcheck // Local fixture response; the receiver verifies its contents.
			return
		}
		if r.URL.Path == "/api/v1/otlp/v1/metrics" && receivedHostMetrics(t, r) {
			hostMetrics.Store(true)
		}
		w.WriteHeader(http.StatusOK)
	}))
	var listen net.ListenConfig
	listener, err := listen.Listen(t.Context(), "tcp", "0.0.0.0:0")
	if err != nil {
		t.Fatal(err)
	}
	if err := endpoint.Listener.Close(); err != nil {
		t.Fatal(err)
	}
	endpoint.Listener = listener
	endpoint.Start()
	t.Cleanup(endpoint.Close)

	config := controllerConfig(t, endpoint.URL)
	config.HTTPAddress = "0.0.0.0:0"
	db := testutil.OpenDatabase(t, config.DatabasePath)
	createAdministrator(t, db)
	token := createAgentKey(t, db)
	controllerURL, _ := startController(t, config)
	agents := agent.NewStore(db)
	store := remoteconfig.NewStore(db)

	container := "arveld-config-test-" + rand.Text()
	docker := func(args ...string) {
		t.Helper()
		ctx, cancel := context.WithTimeout(t.Context(), 30*time.Second)
		defer cancel()
		command := exec.CommandContext(ctx, "docker", args...) //nolint:gosec // Arguments are test-owned values passed directly, without a shell.
		command.Env = slices.DeleteFunc(os.Environ(), func(value string) bool {
			return strings.HasPrefix(value, "ARVELD_HOST_ROOT=")
		})
		output, err := command.CombinedOutput()
		if err != nil {
			t.Fatalf("docker %s: %v\n%s", args[0], err, output)
		}
	}
	arguments := []string{
		"run", "--detach", "--name", container,
		"--add-host", "host.docker.internal:host-gateway",
		"--env", "ARVELD_AGENT_TOKEN=" + token,
		"--env", "ARVELD_URL=" + dockerHostURL(t, controllerURL),
		"--volume", "/var/lib/arveld-agent",
	}
	if mode == "mounted-host" {
		arguments = append(arguments, "--volume", "/:/hostfs:ro")
	} else {
		// Run the native defaults in isolated Linux: no /hostfs mount and no
		// image-provided root override. The executable is identical in both modes.
		arguments = append(arguments, "--env", "ARVELD_HOST_ROOT")
	}
	docker(append(arguments, "arveld-agent:0.161.0-arveld")...)
	t.Cleanup(func() {
		ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
		defer cancel()
		if t.Failed() {
			logs, err := exec.CommandContext(ctx, "docker", "logs", "--tail", "100", container).CombinedOutput() //nolint:gosec // The container name is generated by this test; no shell is used.
			t.Logf("Supervisor logs (error %v):\n%s", err, logs)
		}
		if output, err := exec.CommandContext(ctx, "docker", "rm", "--force", "--volumes", container).CombinedOutput(); err != nil { //nolint:gosec // The container name is generated by this test; no shell is used.
			t.Errorf("remove test container: %v\n%s", err, output)
		}
	})

	var uid agent.InstanceUID
	awaitSupervisor(t, "initial compiled base confirmation", func() bool {
		registered, err := agents.List(t.Context())
		if err != nil {
			t.Fatal(err)
		}
		if len(registered) != 1 {
			return false
		}
		uid = registered[0].InstanceUID
		status, err := store.Status(t.Context(), uid)
		if errors.Is(err, remoteconfig.ErrNoDesiredRevision) {
			return false
		}
		if err != nil {
			t.Fatal(err)
		}
		if status.State == remoteconfig.ApplyStatusFailed {
			t.Fatal("the Agent rejected its initial host configuration")
		}
		return status.State == remoteconfig.ApplyStatusApplied && status.LastWorking != nil
	})
	awaitSupervisor(t, "host measurements through authenticated OTLP", hostMetrics.Load)

	// Keep the real Supervisor connected: API creation must publish and push
	// the Monitor configuration without restarting the Agent.
	body, err := json.Marshal(map[string]any{
		"name": "Health", "agent_instance_uid": uid.String(),
		"endpoint": dockerHostURL(t, endpoint.URL) + "/health", "method": http.MethodPost,
		"body": `{"ready":"$literal"}`, "headers": map[string]string{"Authorization": "Bearer $synthetic"},
		"validations":      []map[string]any{{"type": "json_path", "path": "ready", "equals": "true"}},
		"interval_seconds": 10, "timeout_seconds": 2,
	})
	if err != nil {
		t.Fatal(err)
	}
	request, err := http.NewRequestWithContext(t.Context(), http.MethodPost,
		controllerURL+"/api/v1/monitors/http", bytes.NewReader(body))
	if err != nil {
		t.Fatal(err)
	}
	request.Header.Set("Content-Type", "application/json")
	request.AddCookie(loginController(t, controllerURL))
	response := doControllerRequest(t, request)
	if err := response.Body.Close(); err != nil {
		t.Fatal(err)
	}
	if response.StatusCode != http.StatusCreated {
		t.Fatalf("create HTTP Monitor = %d, want 201", response.StatusCode)
	}
	awaitSupervisor(t, "compiled HTTP Monitor confirmation and execution", func() bool {
		status, err := store.Status(t.Context(), uid)
		if err != nil {
			t.Fatal(err)
		}
		return status.State == remoteconfig.ApplyStatusApplied && status.LastWorking != nil &&
			*status.LastWorking.Revision == status.Desired.Number && probes.Load() > 0
	})
	working, err := store.Desired(t.Context(), uid)
	if err != nil {
		t.Fatal(err)
	}

	docker("stop", "--time", "5", container)
	invalid, err := os.ReadFile("../../internal/opamp/testdata/remote-config-runtime-failure.yaml")
	if err != nil {
		t.Fatal(err)
	}
	// Recovery must follow a startup failure, not rejection of an unknown component.
	docker("run", "--rm",
		"--env", "ARVELD_DIAGNOSTIC_CONFIG="+string(invalid),
		"arveld-agent:0.161.0-arveld", "collector", "validate", "--config=env:ARVELD_DIAGNOSTIC_CONFIG")
	failed, err := store.Save(t.Context(), uid, invalid)
	if err != nil {
		t.Fatal(err)
	}
	docker("start", container)
	awaitSupervisor(t, "runtime failure and local recovery", func() bool {
		status, err := store.Status(t.Context(), uid)
		if err != nil {
			t.Fatal(err)
		}
		return status.State == remoteconfig.ApplyStatusFailed && status.Desired.Number == failed.Number &&
			status.LastFailure != nil && status.LastFailure.Revision != nil && *status.LastFailure.Revision == failed.Number &&
			status.LastWorking != nil && *status.LastWorking.Revision == working.Number &&
			status.Reported != nil && status.Reported.Status == remoteconfig.ApplyStatusApplied &&
			status.Reported.Revision != nil && *status.Reported.Revision == working.Number
	})
	// Observe actual Monitor activity after recovery, not merely an APPLIED report.
	before := probes.Load()
	awaitSupervisor(t, "HTTP Monitor resumed after local recovery", func() bool { return probes.Load() > before })
}

func receivedHostMetrics(t *testing.T, request *http.Request) bool {
	t.Helper()
	var reader io.Reader = request.Body
	if request.Header.Get("Content-Encoding") == "gzip" {
		decompressed, err := gzip.NewReader(request.Body)
		if err != nil {
			t.Error(err)
			return false
		}
		defer func() {
			if err := decompressed.Close(); err != nil {
				t.Error(err)
			}
		}()
		reader = decompressed
	}
	body, err := io.ReadAll(reader)
	if err != nil {
		t.Error(err)
		return false
	}
	decoder := pmetric.ProtoUnmarshaler{}
	metrics, err := decoder.UnmarshalMetrics(body)
	if err != nil {
		t.Error(err)
		return false
	}
	for _, resource := range metrics.ResourceMetrics().All() {
		for _, scope := range resource.ScopeMetrics().All() {
			for _, metric := range scope.Metrics().All() {
				if metric.Name() == "system.uptime" && metric.Type() == pmetric.MetricTypeGauge && metric.Gauge().DataPoints().Len() > 0 {
					return metric.Gauge().DataPoints().At(0).DoubleValue() > 0
				}
			}
		}
	}
	return false
}

func dockerHostURL(t *testing.T, raw string) string {
	t.Helper()
	parsed, err := url.Parse(raw)
	if err != nil {
		t.Fatal(err)
	}
	return "http://host.docker.internal:" + parsed.Port()
}

func awaitSupervisor(t *testing.T, description string, ready func() bool) {
	t.Helper()
	ctx, cancel := context.WithTimeout(t.Context(), 60*time.Second)
	defer cancel()
	ticker := time.NewTicker(200 * time.Millisecond)
	defer ticker.Stop()
	for !ready() {
		select {
		case <-ctx.Done():
			t.Fatalf("timed out waiting for %s: %v", description, ctx.Err())
		case <-ticker.C:
		}
	}
}
