//go:build docker

package agent_test

import (
	"context"
	"crypto/rand"
	"errors"
	"net"
	"net/http"
	"os/exec"
	"testing"
	"time"
)

func TestAgentRequestsOpAMPWithEnvironment(t *testing.T) {
	var listenConfig net.ListenConfig
	listener, err := listenConfig.Listen(t.Context(), "tcp", "0.0.0.0:0")
	if err != nil {
		t.Fatal(err)
	}
	received := make(chan *http.Request, 1)
	server := &http.Server{
		ReadHeaderTimeout: 5 * time.Second,
		Handler: http.HandlerFunc(func(response http.ResponseWriter, request *http.Request) {
			select {
			case received <- request.Clone(request.Context()):
			default:
			}
			response.WriteHeader(http.StatusServiceUnavailable)
		}),
	}
	t.Cleanup(func() {
		if err := server.Close(); err != nil {
			t.Errorf("close test server: %v", err)
		}
	})
	go func() {
		if err := server.Serve(listener); err != nil && !errors.Is(err, http.ErrServerClosed) {
			t.Errorf("serve test endpoint: %v", err)
		}
	}()
	_, port, err := net.SplitHostPort(listener.Addr().String())
	if err != nil {
		t.Fatal(err)
	}

	container := "arveld-agent-startup-" + rand.Text()
	t.Cleanup(func() {
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		if output, err := exec.CommandContext(ctx, "docker", "rm", "--force", container).CombinedOutput(); err != nil { //nolint:gosec // The container name is generated by this test, and no shell is used.
			t.Errorf("remove test container: %v\n%s", err, output)
		}
	})
	ctx, cancel := context.WithTimeout(t.Context(), 20*time.Second)
	defer cancel()
	token := rand.Text()
	command := exec.CommandContext(ctx, "docker", "run", "--detach", //nolint:gosec // Arguments contain only test-generated values, and no shell is used.
		"--name", container,
		"--add-host", "host.docker.internal:host-gateway",
		"--env", "ARVELD_AGENT_TOKEN="+token,
		"--env", "ARVELD_URL=http://host.docker.internal:"+port+"/arveld/",
		"arveld-agent:0.161.0-arveld",
	)
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("start agent: %v\n%s", err, output)
	}
	select {
	case request := <-received:
		if request.Method != http.MethodGet || request.URL.Path != "/arveld/v1/opamp" {
			t.Errorf("OpAMP request = %s %s, want GET /arveld/v1/opamp", request.Method, request.URL.Path)
		}
		if request.Header.Get("Upgrade") != "websocket" {
			t.Error("OpAMP request must initiate a WebSocket connection")
		}
		if request.Header.Get("Authorization") != "Bearer "+token {
			t.Error("OpAMP request must authenticate with the supplied agent token")
		}
	case <-ctx.Done():
		logsContext, stopLogs := context.WithTimeout(t.Context(), 5*time.Second)
		defer stopLogs()
		logs, err := exec.CommandContext(logsContext, "docker", "logs", container).CombinedOutput() //nolint:gosec // The container name is generated by this test, and no shell is used.
		t.Fatalf("agent did not request OpAMP: %v; logs error: %v\n%s", ctx.Err(), err, logs)
	}
}
